---
- name: Configure GitHub Self-hosted Runner in Docker
  hosts: ovh_vps
  become: true
  gather_facts: true

  vars_files:
    - "../inventory/group_vars/secrets.yml"

  roles:
    - role: docker
    - role: github_runner_docker
