---
github_runner_project_dir: /opt/compose/github-runner
github_runner_image: "myoung34/github-runner:latest"
github_runner_name: "{{ ansible_hostname }}-runner"
github_runner_labels: "linux,x64,docker"
github_runner_repo_url: ""
github_runner_token: ""
# Or use GITHUB_ACCESS_TOKEN for auto-refreshing tokens
github_runner_access_token: ""
github_runner_extra_env: []
