---
services:
  openresty:
    image: openresty/openresty:1.27.1.2-0-alpine
    container_name: openresty-basic-auth
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./auth/users.htpasswd:/etc/nginx/auth/users.htpasswd:ro
      - ./html:/usr/local/openresty/nginx/html:ro
